name: Publish to npm

on: [push, pull_request, release, create]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
          if: github.event_name == 'create' && github.event.ref_type == 'tag'
          env:
            NODE_AUTH_TOKEN: ${{secrets.npm_token}}
